#!/usr/bin/env bash
# It configures a brand new Ubuntu machine
sudo apt-get -y update
sudo apt-get install -y nginx
sudo sed -i "11i\add_header X-Served-By $HOSTNAME;" /etc/nginx.nginx.conf
sudo service nginx restart
