#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 23761-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 23761-web-02 18.232.38.114:80 check\n\tserver 23761-web-01 18.206.92.122:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
