#!/usr/bin/env bash
#short and sweet fix with 7 or less lines
pkill apache2
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chown 755 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
